version: '3.8'

services:
  atypikhouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atypikhouse
    working_dir: /var/www/html
    env_file: .env
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: atypikhouse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dogomet
      MYSQL_DATABASE: atypikhouse
      MYSQL_USER: asma
      MYSQL_PASSWORD: dogomet
    networks:
      - laravel
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: atypikhouse-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - laravel
    depends_on:
      - mysql
    ports:
      - "8081:80"

  caddy:
    image: caddy:2.4.3
    container_name: atypikhouse-caddy
    networks:
      - laravel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  laravel:
    driver: bridge
