version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - cady_default  # Use the existing network
    ports:
      - "9001:9001"