version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atypikhouse
    restart: always
    ports:
      - 9001:80
    volumes:
      - .:/var/www/html
    env_file:
      - .env
  # caddy:
  #   image: abiosoft/caddy:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/Caddyfile
  #     - /var/www/html:/srv
