version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8083:80"
    networks:
      - laravel_network

  db:
    image: mysql:5.7
    container_name: laravel-mysql
    environment:
      MYSQL_ALLOWEMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: atypikhouse
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "8082:80"
    networks:
      - laravel_network

networks:
  laravel_network:
