version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atypikhouse
    restart: always
    ports:
      - 9003:80
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "8003:80"
      - "444:443"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:




  # caddy:
  #   image: abiosoft/caddy:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/Caddyfile
  #     - /var/www/html:/srv
