version: '3'

networks: 
    bdd_mysql-phpmyadmin:
              driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
           # - mysql
        networks: 
            - bdd_mysql-phpmyadmin

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: atypikhouse
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "${LARAVEL_HOST_PORT}:${LARAVEL_DOCKER_CONTAINER_PORT}"
        networks: 
            - bdd_mysql-phpmyadmin